data_changement=[
    #generale
    ("Je voudrais apporter des modifications à mon application. Pouvez-vous m'aider ?", {"entities": [(12,38,["None"])]}),
    ("Est-il possible de faire des ajustements dans mon application ?", {"entities": [(19,40,["None"])]}),
    ("J'aimerais effectuer des changements dans mon application. Comment puis-je procéder ?", {"entities": [(11,36,["None"])]}),
    ("Je souhaite mettre à jour mon application. Comment faire pour changer des éléments ?", {"entities": [(12,25,["None"])]}),
    ("Y a-t-il un moyen de modifier des éléments dans mon application ?", {"entities": [(21,42,["None"])]}),
    ("Comment puis-je faire des modifications dans mon application ?", {"entities": [(26,39,["None"])]}),
    ("Je veux apporter des changements à mon application. Par où dois je commencer ?", {"entities": [(21,50,["None"])]}),
    # Nom app
    ("Je souhaite changer le nom de l'application.", {"entities": [(23,43,["nomApplication"])]}),
    ("Pouvez-vous m'aider à modifier le nom de l'application ?", {"entities": [(34,54,["nomApplication"])]}),
    ("Est il possible de changer le nom de l'application ?", {"entities": [(30,50,["nomApplication"])]}),
    ("Je veux mettre à jour le nom de l'application.", {"entities": [(25,45,["nomApplication"])]}),
    ("Peut-on changer le nom de l'application ?", {"entities": [(19,39,["nomApplication"])]}),
    ("Je voudrais modifier le nom de l'application.", {"entities": [(24,44,["nomApplication"])]}),
    ("Comment puis-je changer le nom de l'application ?", {"entities": [(27,47,["nomApplication"])]}),
    ("Je souhaite changer le nom de mon application.", {"entities": [(23,45,["nomApplication"])]}),
    ("Pouvez-vous m'expliquer comment changer le nom de l'application ?", {"entities": [(43,63,["nomApplication"])]}),
    ("J'aimerais savoir comment changer le nom de l'application.", {"entities": [(37,57,["nomApplication"])]}),

    ("Je souhaite changer le nom de l'application en MyAppGenial.", {"entities": [ (47,58, ["nomApplication","new_valeur"])]}),
    ("Pouvez-vous m'aider à modifier le nom de l'application pour MonAppMeilleure ?", {"entities": [ (60,75, ["nomApplication","new_valeur"])]}),
    ("Est il possible de changer le nom de l'application en SuperApp ?", {"entities": [ (54, 62, ["nomApplication","new_valeur"])]}),
    ("Je veux mettre à jour le nom de l'application vers NouveauNomApp.", {"entities": [ (51,64, ["nomApplication","new_valeur"])]}),
    ("Peut-on changer le nom de l'application en NomApplicationCool ?", {"entities": [(43, 61, ["nomApplication","new_valeur"])]}),
    ("Je voudrais modifier le nom de l'application pour AppAmeliorée.", {"entities": [(50, 62, ["nomApplication","new_valeur"])]}),
    ("Comment puis-je changer le nom de l'application en MonAppParfaite ?", {"entities": [(51, 65, ["nomApplication","new_valeur"])]}),
    ("Je souhaite changer le nom de mon application en SuperAppGenius.", {"entities": [ (49,63, ["nomApplication","new_valeur"])]}),
    ("Pouvez-vous m'expliquer comment changer le nom de l'application en TopApp ?", {"entities": [ (67,73, ["nomApplication","new_valeur"])]}),
    ("J'aimerais savoir comment changer le nom de l'application en MyAppUltimate.", {"entities": [(61,74, ["nomApplication","new_valeur"])]}),

    #frontend
    ("Je souhaite changer l'espace de travail pour la partie frontend.", {"entities": [(55,63, ["frontendWorkspace"])]}),
    ("Pouvez-vous m'aider à modifier l'espace de travail de la partie web ?", {"entities": [(33,67, ["frontendWorkspace"])]}),
    ("Est il possible de changer l'espace de travail pour le frontend ?", {"entities": [(29,63, ["frontendWorkspace"])]}),
    ("Je veux mettre à jour l'espace de travail pour la partie web.", {"entities": [(24,60, ["frontendWorkspace"])]}),
    ("Peut on changer l'espace de travail de la partie frontend ?", {"entities": [(18,57, ["frontendWorkspace"])]}),
    ("Je voudrais modifier l'espace de travail pour l'interface web.", {"entities": [(23,61, ["frontendWorkspace"])]}),
    ("Comment puis-je changer l'espace de travail de la partie client ?", {"entities": [(26,63, ["frontendWorkspace"])]}),
    ("Je souhaite changer l'espace de travail pour la partie web de mon application.", {"entities": [(22,58, ["frontendWorkspace"])]}),
    ("Pouvez-vous m'expliquer comment changer l'espace de travail de la partie frontend ?", {"entities": [(42,81, ["frontendWorkspace"])]}),
    ("J'aimerais savoir comment changer l'espace de travail pour l'interface utilisateur.", {"entities": [(36,82, ["frontendWorkspace"])]}),

    ("Je souhaite changer l'espace de travail pour la partie frontend en 'NouvelEspaceFrontend'.", {"entities": [ (68,88, ["frontendWorkspace","new_valeur"])]}),
    ("Pouvez-vous m'aider à modifier l'espace de travail de la partie web vers 'NouveauFrontendWorkspace' ?", {"entities": [ (74, 98, ["frontendWorkspace","new_valeur"])]}),
    ("Est il possible de changer l'espace de travail pour le frontend en 'EspaceWebModifié' ?", {"entities": [ (68,84, ["frontendWorkspace","new_valeur"])]}),
    ("Je veux mettre à jour l'espace de travail pour la partie web avec 'NouveauWorkspace'.", {"entities": [ (67,83, ["frontendWorkspace","new_valeur"])]}),
    ("Peut-on changer l'espace de travail de la partie frontend en 'FrontendRenouvelé' ?", {"entities": [ (62,79, ["frontendWorkspace","new_valeur"])]}),
    ("Je voudrais modifier l'espace de travail pour l'interface web vers 'EspaceModifié'.", {"entities": [ (68,81, ["frontendWorkspace","new_valeur"])]}),
    ("Comment puis-je changer l'espace de travail de la partie client à 'NouveauClientWorkspace' ?", {"entities": [ (67,89, ["frontendWorkspace","new_valeur"])]}),
    ("Je souhaite changer l'espace de travail pour la partie web de mon application en 'EspaceNouveau'.", {"entities": [ (82,95, ["frontendWorkspace","new_valeur"])]}),
    ("Pouvez-vous m'expliquer comment changer l'espace de travail de la partie frontend en 'WorkspaceActualisé' ?", {"entities": [(86,104, ["frontendWorkspace","new_valeur"])]}),
    ("J'aimerais savoir comment changer l'espace de travail pour l'interface utilisateur vers 'NouvelEspaceClient'.", {"entities": [ (89,107, ["frontendWorkspace","new_valeur"])]}),


    #backend
    ("Je souhaite changer l'espace de travail pour la partie serveur.", {"entities": [(22,62, ["backendWorkspace"])]}),
    ("Pouvez-vous m'aider à modifier l'espace de travail de la partie serveur ?", {"entities": [(33,71, ["backendWorkspace"])]}),
    ("Est il possible de changer l'espace de travail pour le backend ?", {"entities": [(29,62, ["backendWorkspace"])]}),
    ("Je veux mettre à jour l'espace de travail pour la partie serveur.", {"entities": [(24,64,[ "backendWorkspace"])]}),
    ("Peut-on changer l'espace de travail de la partie serveur ?", {"entities": [(18,56, ["backendWorkspace"])]}),
    ("Je voudrais modifier l'espace de travail pour le serveur.", {"entities": [(21,56, ["backendWorkspace"])]}),
    ("Comment puis-je changer l'espace de travail de la partie backend ?", {"entities": [(26,64, ["backendWorkspace"])]}),
    ("Je souhaite changer l'espace de travail pour la partie serveur de mon application.", {"entities": [(22,62, ["backendWorkspace"])]}),
    ("Pouvez-vous m'expliquer comment changer l'espace de travail de la partie backend ?", {"entities": [(42,80, ["backendWorkspace"])]}),
    ("J'aimerais savoir comment changer l'espace de travail pour le serveur.", {"entities": [(36,69, ["backendWorkspace"])]}),

    ("Je souhaite changer l'espace de travail backend en 'MonEspaceBackend'.", {"entities": [ (52,68, ["backendWorkspace","new_valeur"])]}),
    ("Pouvez-vous m'aider à modifier l'espace de travail du backend pour 'NouveauBackend' ?", {"entities": [ (68,82, ["backendWorkspace","new_valeur"])]}),
    ("Est il possible de changer l'espace de travail pour le backend en 'Backend2023' ?", {"entities": [ (67,78, ["backendWorkspace","new_valeur"])]}),
    ("Je veux mettre à jour l'espace de travail backend avec 'NouvelEspace' comme nom.", {"entities": [ (56,68, ["backendWorkspace","new_valeur"])]}),
    ("Peut-on changer l'espace de travail du backend en 'EspaceModifié' ?", {"entities": [ (51,64, ["backendWorkspace","new_valeur"])]}),
    ("Comment puis-je changer l'espace de travail de la partie backend en 'NouveauWorkspace' ?", {"entities": [ (69,85, ["backendWorkspace","new_valeur"])]}),
    ("Je souhaite changer l'espace de travail backend pour 'EspaceDeTravail2022'.", {"entities": [ (54,73, ["backendWorkspace","new_valeur"])]}),
    ("Pouvez-vous m'expliquer comment changer l'espace de travail de la partie backend en 'BackendWorkspace' ?", {"entities": [ (85,101,["backendWorkspace","new_valeur"])]}),
    ("J'aimerais savoir comment changer l'espace de travail pour le backend en 'NouveauBackendEspace'.", {"entities": [ (74,94, ["backendWorkspace","new_valeur"])]}),

    #langues
    ("Je souhaite changer les langues prises en charge.", {"entities": [(24,31, ["langue"])]}),
    ("Pouvez-vous m'aider à modifier les langages supportés ?", {"entities": [(35,43, ["langue"])]}),
    ("Est il possible de changer les langues de l'application ?", {"entities": [(31,38, ["langue"])]}),
    ("Peut-on changer les langages utilisés dans l'application ?", {"entities": [(20,28, ["langue"])]}),
    ("Je voudrais modifier les langues de mon application.", {"entities": [(25,32, ["langue"])]}),
    ("Comment puis-je changer les langages supportés par l'application ?", {"entities": [(28,36, ["langue"])]}),
    ("Je souhaite changer les langues de mon projet.", {"entities": [(24,31, ["langue"])]}),
    ("Pouvez-vous m'expliquer comment modifier les langages de l'application ?", {"entities": [(45,53,[ "langue"])]}),
    ("J'aimerais savoir comment mettre à jour les langages pris en charge.", {"entities": [(44,52, ["langue"])]}),

    ("Je souhaite ajouter une nouvelle langue à mon application : l'espagnol.", {"entities": [ (62,70, ["langue","new_valeur","add"])]}),
    ("Pouvez-vous m'aider à définir une nouvelle langue pour mon projet ? J'aimerais ajouter le chinois.", {"entities": [ (90,97, ["langue","new_valeur","add"])]}),
    ("Est-il possible de spécifier une langue différente pour mon application ? Je voudrais ajouter l'italien.", {"entities": [ (96,103, ["langue","new_valeur","add"])]}),
    ("Je veux mettre à jour les langues de mon application. Pourriez-vous ajouter le russe ?", {"entities": [ (79,84, ["langue","new_valeur","add"])]}),
    ("Peut-on changer la langue principale de l'application ? J'aimerais ajouter l'arabe.", {"entities": [ (77,82, ["langue","new_valeur","add"])]}),
    ("Je voudrais modifier les langues de mon projet. Ajoutez le portugais, s'il vous plaît.", {"entities": [(59,68, ["langue","new_valeur","add"])]}),
    ("Comment puis-je ajouter une nouvelle langue à mon application ? Je souhaite inclure le japonais.", {"entities": [ (87,95, ["langue","new_valeur","add"])]}),
    ("Je souhaite supprimer la langue espagnole de mon application.", {"entities": [ (32,41, ["langue","new_valeur","delete"])]}),
    ("Pouvez-vous m'aider à remplacer le français par l'allemand dans mon projet ?", {"entities": [ (35,43, ["langue","new_valeur","delete"]), (50,58, ["langue","new_valeur","add"])]}),
    ("Est-il possible de retirer l'italien de la liste des langues supportées ?", {"entities": [(29,36, ["langue","new_valeur","delete"])]}),
    ("Je veux enlever le russe et le chinois des langues disponibles et ajouter le coréen.", {"entities": [ (19,24, ["langue","new_valeur","delete"]), (31,38, ["langue","new_valeur","delete"]), (77,83, ["langue","new_valeur","add"])]}),


    #profilsPartieServeur
    ("Je souhaite changer les profils de la partie serveur de dev et test à prod et pre-prod.", {"entities": [ (56,59, ["profilsPartieServeur","new_valeur","delete"]), (63,67,["profilsPartieServeur","new_valeur","delete"]), (70,74, ["profilsPartieServeur","new_valeur","add"]),(78,86, ["profilsPartieServeur","new_valeur","add"])]}),
    ("Pouvez-vous m'aider à remplacer les profils de développement et de test par production et pre-production ?", {"entities": [ (47,60, ["profilsPartieServeur","new_valeur","delete"]), (67,71, ["profilsPartieServeur","new_valeur","delete"]), (76,86,["profilsPartieServeur","new_valeur","add"]), (90,104, ["profilsPartieServeur","new_valeur","add"])]}),
    ("Est il possible de changer les profils de prod et pre-prod pour dev et test ?", {"entities": [ (42, 46, ["profilsPartieServeur","new_valeur","delete"]), (50, 58, ["profilsPartieServeur","new_valeur","delete"]), (64, 67, ["profilsPartieServeur","new_valeur","add"]), (71, 75, ["profilsPartieServeur","new_valeur","add"])]}),
    ("Je veux remplacer les profils de test et pre-prod par dev et prod.", {"entities": [ (33,37,["profilsPartieServeur","new_valeur","delete"]), (41,49, ["profilsPartieServeur","new_valeur","delete"]), (54,57, ["profilsPartieServeur","new_valeur","add"]), (61,65,["profilsPartieServeur","new_valeur","add"])]}),
    ("Peut-on changer les profils de développement et de pre-production à production et test ?", {"entities": [ (31,44, ["profilsPartieServeur","new_valeur","delete"]), (51,65, ["profilsPartieServeur","new_valeur","delete"]), (68,78, ["profilsPartieServeur","new_valeur","add"]), (82,86, ["profilsPartieServeur","new_valeur","add"])]}),
    ("Je voudrais modifier les profils de prod et test en dev et pre-prod.", {"entities": [(36,40, ["profilsPartieServeur","new_valeur","delete"]), (44,48,["profilsPartieServeur","new_valeur","delete"]), (52,55,["profilsPartieServeur","new_valeur","add"]), (59,67, ["profilsPartieServeur","new_valeur","add"])]}),
    ("Je voudrais ajouter le profil de pré-production pour la partie serveur.", {"entities": [ (33,47,["profilsPartieServeur","new_valeur","add"])]}),
    

    # NZID DES EXEMPLES AAL PROFILS  w nkml les microservices
]