data_resume = [

    #nomApplication 
    ("Pouvez-vous me rappeler le nom de mon application ?", {"entities": [(27,49, "nomApplication")]}),
    ("Quel était le nom que j'ai donné à mon application ?", {"entities": [(14,50, "nomApplication")]}),
    ("Résumez le nom de l'application que j'ai spécifié.", {"entities": [(11,31, "nomApplication")]}),
    ("Revenons sur le nom que j'ai choisi pour mon application.", {"entities": [(16,56, "nomApplication")]}),
    ("Peux-tu me dire le nom de l'application que j'ai enregistré ?", {"entities": [(19,39, "nomApplication")]}),
    ("Quel est le nom que j'ai indiqué pour mon application ?", {"entities": [(12,53, "nomApplication")]}),
    ("Je veux un rappel du nom de l'application que j'ai inscrit.", {"entities": [(21,58, "nomApplication")]}),
    ("Pourriez-vous récapituler le nom que j'ai mis pour mon application ?", {"entities": [(29,66, "nomApplication")]}),
    ("Quel nom d'application ai-je enregistré ?", {"entities": [(5,22, "nomApplication")]}),
    ("Répétez le nom de l'application que j'ai spécifié.", {"entities": [(11,31, "nomApplication")]}),
    ("Je veux savoir ce que j'ai deja introduit comme valeur pour le nom de mon application", {"entities": [(63,85, "nomApplication")]}),
    ("Rappelez-moi le nom que j'ai attribué à mon application, s'il vous plaît.", {"entities": [(16,19, "nomApplication")]}),
    ("Quel était le nom que j'ai réservé pour mon application ?", {"entities": [(14,17, "nomApplication")]}),
    ("Affichez le nom que j'ai enregistré pour mon application.", {"entities": [(12,15, "nomApplication")]}),
    ("Pouvez-vous me donner à nouveau le nom de l'application que j'ai spécifié ?", {"entities": [(35,55, "nomApplication")]}),
    ("Résumez le nom que j'ai choisi pour mon projet d'application.", {"entities": [(11,14, "nomApplication")]}),
    ("Je souhaite connaître le nom que j'ai précédemment indiqué pour mon application.", {"entities": [(25,28, "nomApplication")]}),
    ("Quel nom d'application ai-je enregistré dans le système ?", {"entities": [(5,22, "nomApplication")]}),
    ("Revenons sur le nom que j'ai donné à mon application. Pouvez-vous me le rappeler ?", {"entities": [(16,19, "nomApplication")]}),
    ("Affichez le nom que j'ai utilisé pour désigner mon application, s'il vous plaît.", {"entities": [(12,15, "nomApplication")]}),
    ("J'aimerais revoir le nom que j'ai saisi pour mon application. Pouvez-vous me l'afficher ?", {"entities": [(21,24, "nomApplication")]}),
    

    #frontendWorkspace
    ("Pouvez-vous me rappeler le nom de mon espace de travail frontend ?", {"entities": [(27,64, "frontendWorkspace")]}),
    ("Quel était le nom que j'ai donné à ma zone de travail côté client ?", {"entities": [(38,65, "frontendWorkspace")]}),
    ("Résumez l'espace de travail frontend que j'ai spécifié.", {"entities": [(10,36, "frontendWorkspace")]}),
    ("Revenons sur le nom de mon espace de travail côté client.", {"entities": [(27,56, "frontendWorkspace")]}),
    ("Peux-tu me dire comment s'appelle mon espace de travail frontend ?", {"entities": [(38,64, "frontendWorkspace")]}),
    ("Quel est le nom que j'ai indiqué pour mon espace de travail côté client ?", {"entities": [(42,71, "frontendWorkspace")]}),
    ("Je veux un rappel du nom de mon espace de travail frontend.", {"entities": [(32,58, "frontendWorkspace")]}),
    ("Pourriez-vous récapituler l'espace de travail frontend que j'ai spécifié ?", {"entities": [(28,54, "frontendWorkspace")]}),
    ("Quel espace de travail côté client ai-je enregistré ?", {"entities": [(5,34, "frontendWorkspace")]}),
    ("Répétez le nom de mon espace de travail côté client.", {"entities": [(22,51, "frontendWorkspace")]}),
    ("Quel est le nom de ma zone de travail frontend ?", {"entities": [(22,46, "frontendWorkspace")]}),
    ("Dis-moi le nom de mon environnement frontend.", {"entities": [(11,44, "frontendWorkspace")]}),
    ("Pouvez-vous me rappeler le nom de mon environnement de travail côté client ?", {"entities": [(27,74, "frontendWorkspace")]}),
    ("Quel était le nom que j'ai attribué à ma zone de travail frontend ?", {"entities": [(41,65, "frontendWorkspace")]}),
    ("Résumez l'espace de travail frontend que j'ai précédemment spécifié.", {"entities": [(10,36, "frontendWorkspace")]}),
    ("Revenons sur le nom de mon environnement de travail côté client. Pouvez-vous me le rappeler ?", {"entities": [(16,63, "frontendWorkspace")]}),
    ("Peux-tu me dire comment s'appelle mon espace de travail côté client, s'il te plaît ?", {"entities": [(38,67, "frontendWorkspace")]}),
    ("Quel est le nom que j'ai indiqué pour ma zone de travail frontend ?", {"entities": [(41,65, "frontendWorkspace")]}),
    ("Je souhaite obtenir un rappel du nom de mon espace de travail frontend.", {"entities": [(33,70, "frontendWorkspace")]}),
    ("Pourriez-vous récapituler l'espace de travail côté client que j'ai spécifié ?", {"entities": [(28,57, "frontendWorkspace")]}),
    ("Quel environnement de travail côté client ai-je enregistré dans le système ?", {"entities": [(5,41, "frontendWorkspace")]}),
    ("Répétez le nom de mon espace de travail côté client, s'il vous plaît.", {"entities": [(11,51, "frontendWorkspace")]}),
    ("Quel est le nom de ma zone de travail frontend que j'ai enregistré ?", {"entities": [(22,46, "frontendWorkspace")]}),
    ("Dis-moi le nom de mon environnement frontend que j'ai spécifié.", {"entities": [(11,44, "frontendWorkspace")]}),


    #backendWorkspace
    ("Pouvez-vous me rappeler le nom de mon espace de travail backend ?", {"entities": [(38,63, "backendWorkspace")]}),
    ("Quel était le nom que j'ai donné à ma zone de travail côté serveur ?", {"entities": [(38,66, "backendWorkspace")]}),
    ("Résumez l'espace de travail backend que j'ai spécifié.", {"entities": [(10,35, "backendWorkspace")]}),
    ("Revenons sur le nom de mon espace de travail côté serveur.", {"entities": [(27,57, "backendWorkspace")]}),
    ("Peux-tu me dire comment s'appelle mon espace de travail backend ?", {"entities": [(38,63, "backendWorkspace")]}),
    ("Quel est le nom que j'ai indiqué pour mon espace de travail côté serveur ?", {"entities": [(42,72, "backendWorkspace")]}),
    ("Je veux un rappel du nom de mon espace de travail backend.", {"entities": [(32,57, "backendWorkspace")]}),
    ("Pourriez-vous récapituler l'espace de travail backend que j'ai spécifié ?", {"entities": [(28,53, "backendWorkspace")]}),
    ("Quel espace de travail côté serveur ai-je enregistré ?", {"entities": [(5,35, "backendWorkspace")]}),
    ("Répétez le nom de mon espace de travail côté serveur.", {"entities": [(22,52, "backendWorkspace")]}),
    ("Quel est le nom de ma zone de travail backend ?", {"entities": [(22,45, "backendWorkspace")]}),
    ("Dis-moi le nom de mon environnement backend.", {"entities": [(11,43, "backendWorkspace")]}),

    #profilsPartieServeur
    ("Pouvez-vous me rappeler le profil de ma partie serveur ?", {"entities": [(27,54, "profilsPartieServeur")]}),
    ("Quel profil ai-je spécifié pour la partie serveur de mon application ?", {"entities": [(5,11, "profilsPartieServeur")]}),
    ("Résumez le profil de la partie serveur que j'ai indiqué.", {"entities": [(11,38, "profilsPartieServeur")]}),
    ("Revenons sur le profil de ma partie serveur.", {"entities": [(16,43, "profilsPartieServeur")]}),
    ("Peux-tu me dire quel profil j'ai choisi pour ma partie serveur ?", {"entities": [(21,27, "profilsPartieServeur")]}),
    ("Quel est le profil que j'ai défini pour ma partie serveur ?", {"entities": [(12,18, "profilsPartieServeur")]}),
    ("Je veux un rappel du profil de ma partie serveur.", {"entities": [(21,48, "profilsPartieServeur")]}),
    ("Pourriez-vous récapituler le profil de la partie serveur que j'ai spécifié ?", {"entities": [(29,56, "profilsPartieServeur")]}),
    ("Quel profil ai-je enregistré pour la partie serveur ?", {"entities": [(5,11, "profilsPartieServeur")]}),
    ("Répétez le profil de ma partie serveur.", {"entities": [(11,38, "profilsPartieServeur")]}),
    ("Quel est le profil de ma partie serveur ?", {"entities": [(12,39, "profilsPartieServeur")]}),
    ("Dis-moi le profil de ma partie serveur.", {"entities": [(11,38, "profilsPartieServeur")]}),

    #microservices
    ("Quels microservices ai-je sélectionnés pour mon projet ?", {"entities": [(6,19, "microservices")]}),
    ("J'aimerais revoir les microservices que j'ai spécifiés", {"entities": [(22,35, "microservices")]}),
    ("Pourriez-vous m'indiquer les microservices que j'ai enregistrés ?", {"entities": [(29,42, "microservices")]}),
    ("Donnez-moi une liste des microservices que j'ai définis.", {"entities": [(25,38, "microservices")]}),
    ("Je veux un rappel des microservices que j'ai choisis pour mon application.", {"entities": [(22,35, "microservices")]}),
    ("Pouvez-vous me dire quels microservices sont enregistrés pour mon projet ?", {"entities": [(26,39, "microservices")]}),
    ("Affichez les microservices que j'ai configurés.", {"entities": [(13,26, "microservices")]}),
    ("Besoin de connaître les microservices que j'ai spécifiés.", {"entities": [(24,37, "microservices")]}),
    ("Répétez la liste des microservices que j'ai enregistrés.", {"entities": [(21,34, "microservices")]}),
    ("Répétez les microservices que j'ai définis.", {"entities": [(12,25, "microservices")]}),
    ("Quels sont les microservices que j'ai configurés pour mon application ?", {"entities": [(15,28, "microservices")]}),
    ("Quels sont les microservices que j'ai mentionnés précédemment ?", {"entities": [(15,28, "microservices")]}),

    #langue
    ("Pourriez-vous me rappeler les langues que j'ai sélectionnées ?", {"entities": [(30,37, "langue")]}),
    ("Affichez la liste des langues que j'ai enregistrées.", {"entities": [(22,29, "langue")]}),
    ("Quelles langues ai-je spécifiées pour mon application ?", {"entities": [(8,15, "langue")]}),
    ("Pouvez-vous me dire quelles langues sont configurées pour mon projet ?", {"entities": [(28,35, "langue")]}),
    ("Besoin de connaître les langues que j'ai choisies.", {"entities": [(24,31, "langue")]}),
    ("Répétez la liste des langues que j'ai définies.", {"entities": [(11,28, "langue")]}),
    ("Quelles sont les langues que j'ai précédemment enregistrées ?", {"entities": [(17,24, "langue")]}),





    # ("Pouvez vous me rappeler les détails que j'ai fournis sur mon application ?", {"entities": [(28,35, "none")]}),
    # ("Pouvez vous me rappeler ce que j'ai dit précédemment ?", {"entities": [(15,23, "none")]}),
    # ("Quelles informations ai-je fournies jusqu'à présent ?", {"entities": [(8,20, "none")]}),
    # ("Affichez moi un récapitulatif de ce que j'ai introduit.", {"entities": [(16,29, "none")]}),
    # ("Répétez ce que j'ai dit auparavant.", {"entities": [(0,34, "none")]}),
    # ("Pouvez vous rappeler les détails que j'ai fournis ?", {"entities": [(12,21, "none")]}),
    # ("Quelles sont les informations que j'ai déjà mentionnées ?", {"entities": [(17,30, "none")]}),
    # ("Affichez-moi les données que j'ai déjà partagées.", {"entities": [(17,25, "none")]}),
    # ("Quels sont les éléments que j'ai déjà communiqués ?", {"entities": [(15,49, "none")]}),
    # ("Besoin d'un rappel sur les détails que j'ai donnés.", {"entities": [(12,34, "none")]}),
    # ("J'aimerais voir ce que j'ai saisi concernant mon application. Pourriez-vous m'afficher cela ?", {"entities": [(23,60, "none")]}),
    # ("Montrez-moi ce que vous avez enregistré à propos de mon application, s'il vous plaît.", {"entities": [(0,67, "none")]}),
    # ("Besoin d'un rappel sur les détails que j'ai donnés.", {"entities": [(12,34, "none")]}),
    # ("Besoin d'un rappel sur les détails que j'ai donnés.", {"entities": [(12,34, "none")]}),
    # ("Besoin d'un rappel sur les détails que j'ai donnés.", {"entities": [(12,34, "none")]}),
    # ("Besoin d'un rappel sur les détails que j'ai donnés.", {"entities": [(12,34, "none")]}),
    # ("Besoin d'un rappel sur les détails que j'ai donnés.", {"entities": [(12,34, "none")]}),


]